language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  # this fixes SemLock issues on travis
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm" 
  - "sudo apt-get install libzmq3-dev"
  - "python scripts/pypi_mirror_setup.py http://a.pypi.python.org/simple"
  - "pip install cython"
  - "make test_setup"
  - "python setup.py develop"

env:
  matrix: 
    - COMMAND="make test"
    - COMMAND="make cybuild test""

script: "$COMMAND"

notifications:
  email: 
    recipients:
      - vmalloc@gmail.com
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
