language: python

services:
  - redis

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  # this fixes SemLock issues on travis
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm" 
  - "sudo apt-get install libzmq3-dev redis-server"
  - "pip install cython redis"
  - "make test_setup"
  - "python setup.py develop"

env:
  - COMMAND="make test"
  - COMMAND="make cybuild test"

script: "$COMMAND"

matrix:
  exclude:
    - python: "pypy"
      env: COMMAND="make cybuild test"

notifications:
  email: 
    recipients:
      - vmalloc@gmail.com
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
